### ISSUE TITLE
Opto outputs (still units)

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#10]
Opto.sensorRead should be in percents as well.

The reason is, that the Arduino SerialPlotter will not play nicely with values that are an order of magnitude different. Eg. If input runs to 100, you wont see anything on the screen from output.

This of course means, a calibration function is needed.

**Comment by gergelytakacs** [comment]
Tibi, pls. consult the wiki for this, also our discussion today.

**Comment by TiborKonkoly** [comment]
This task is also done, the input of the Opto.sensorRead() function is in percents.

**Comment by gergelytakacs** [comment]
Awesome!
