### ISSUE TITLE
BoBShield: sensorRead() method 

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#104]
The `sensorRead()` mehod
- Must return the position of the ball in mm
- Must correct for the shift in the zero position based on the `calibration()` method
- Must use the Adafruit VL6180X library that is located as the submodule in `src/lib`

@corleone68

**Comment by gergelytakacs** [comment]
I have added the VL6180X library as a submodule.

**Comment by gergelytakacs** [comment]
You guys said you did not have the other submodule (for the VL5x...) working, when you cloned the repo. That is because when working with submodules, you have to initialize them by calling `submodule update --init --recursive`

**Comment by gergelytakacs** [comment]
![image](https://user-images.githubusercontent.com/37662064/56887045-bfe75100-6a70-11e9-8722-73bcbe702ef0.png)
- No `Serial` in the methods.
- Please comment in detail.
- How does the `calibration()` affect this function? (It doesn't). The minimal value should be calibrated, but only if the user has run the calibration sequence. So if it has been calibrated, then the minimum is that value... Instead of using "minimum" you can store "minimum calibrated" - that is then rewritten in the calibration function...
- The `status` flag is very interesting. What sort of errors does the VL6180 produce? Can this be used to e.g. interpolate values if reading fails? Please research the possible errors...
It could be (in pseudocode) - just an idea:
```
if (status == someerror)
  output the previous value... (or some other interpolation)
end
```

**Comment by corleone68** [comment]
solution for cloning AutomationShield library with submodules worked, but it's without characters '<' and '>'

**Comment by gergelytakacs** [comment]
@corleone68 Sure, the <> was only there to denote "insert the URL" here and that the given part is not a literal command. Git syntax doesn't use it, sorry if that was confusing.

**Comment by gergelytakacs** [comment]
@corleone68 @lukasvadovic2

- Just purely to keep consistency for the API for the user, please call the "default" sensor read function `BOBClass::sensorReadMm()` instead of `BOBClass::sensorReadMm()`. All devices have this function... It is fine to leave `sensorReadPerc()` as is, for an alternative. You are also welcome to wrap `sensorReadMm()` in `sensorRead()` to achieve the same effect.
- Why is the sensor reading function returning nothing? (`void BOBClass::sensorReadMm()`). It should return a floating point number.
- You have nicely made a flag that says if the thing has been calibrated (`calibrated=1`) but then you are not really using it. :)

**Comment by corleone68** [comment]
How should we call it please ? Cos those two names are the same
![image](https://user-images.githubusercontent.com/35456504/57210732-0d6a3d80-6fde-11e9-9977-fc88359eae1f.png)

**Comment by gergelytakacs** [comment]
Ok sorry. As it is written in the guide in the sticky note (look up), it
should be sensorRead().

All of the boards have this function name.

Best regards / S pozdravom / Udvozlettel;

Gergely Takacs, PhD.
Associate Professor
___________________________________________________
   web:       gergelytakacs.com
   e-mail: gergelytakacs@gergelytakacs.com
   mobile: +421(0)907 165 720


<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
I'm using Inbox When Ready
<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
to protect my focus.

**Comment by gergelytakacs** [comment]
- Yet again it's an uncommented, mess, so please do comment. 
- Also where did you take "4" from the middle from? Will this be the same for all future shields?
- Why don't you use `sensorRead()` in mm in `sensorReadPerc()` anyways? You can call a method inside a mehtod... I would just ensure that my `sensorRead()` works well. 
- Also the read function does not know if the calibration routine has been launched or not... Why? That's what for the `calibrated` flag is for!
