### ISSUE TITLE
BoBShield: begin()

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#106]
The BoBShield Arduino API shall have a `begin()` method, that can possibly
- set pin modes, if necessary (probably not)
- initialize the `Servo` object and pin
- etc. (e.g. any other initialization task)

@corleone68

**Comment by gergelytakacs** [comment]
![image](https://user-images.githubusercontent.com/37662064/56886415-47cc5b80-6a6f-11e9-84f1-99672f21076e.png)
- No Serial in the code
- Keep naming consistent, this should be `begin()`
- The self-test for the sensor should not be used here, instead you can make a testing example for the entire board, like it is done for the MagnetoShield

**Comment by corleone68** [comment]
understood, thanks for the feedback
Could Servo pin and be initialized in .ino ?

**Comment by gergelytakacs** [comment]
For a quick test yes, but for the final software no.

So, If you are stuck, initialize in *ino. Otherwise experiment and try to
initialize within the BoBShield API.


Best regards / S pozdravom / Udvozlettel;

Gergely Takacs, PhD.
Associate Professor
___________________________________________________
   web:       gergelytakacs.com
   e-mail: gergelytakacs@gergelytakacs.com
   mobile: +421(0)907 165 720


<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
I'm using Inbox When Ready
<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
to protect my focus.

**Comment by gergelytakacs** [comment]
@corleone68 @lukasvadovic2

I do not think `  pinMode(POT_PIN, INPUT);			// set Potentiometer pin` is necessary. It is an analog pin, I don't think you need to set the direction for it...?!?

**Comment by gergelytakacs** [comment]
- Pot input initialization is possibly not necessary.
- Choose a nicer name than `myservo`. Not `butterfly`.

**Comment by raleh** [comment]
Can You @corleone68 or @lukasvadovic2 look at the description of the code on the wiki and advise me how to describe it better.

**Comment by gergelytakacs** [comment]
@raleh Yes, however, due to the unfortunate events please bug @lukasvadovic2 and S. Mlady... (Also he should send me his GitHub handle so I can add him to the project).

**Comment by gergelytakacs** [comment]
Is `pinMode` even needed for analog inputs?
![image](https://user-images.githubusercontent.com/37662064/58008992-c73cd000-7aed-11e9-9747-d911d7b4a582.png)
