### ISSUE TITLE
BoBShield: Electronic and PCB Design

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#107]
- The board should be 3.3 V compatible

**Comment by gergelytakacs** [comment]
![image](https://user-images.githubusercontent.com/37662064/56582523-c17bc980-65d7-11e9-8318-fba1e85755a1.png)

**Comment by gergelytakacs** [comment]
- Use the Magneto Shield (R2 / R3) for reference
- Use the "CA9" sized pot for the design, this is the smaller one we own.
- Use 3.3 V reference and logic (see another issue)

**Comment by TiborKonkoly** [comment]
The schematic and PCB design of the BoB shields first version is included in the attached .zip file. 

[BoB.zip](https://github.com/gergelytakacs/AutomationShield/files/3109671/BoB.zip)

**Comment by gergelytakacs** [comment]
Thank you @TiborKonkoly , will try to review your design ASAP.

**Comment by TiborKonkoly** [comment]
I have made the requested changes. We can make a final check tomorrow at school, I would like to check the placement of the connectors together, just to make it sure.

So here is the scheme:
![Schema](https://user-images.githubusercontent.com/37699408/56686624-ad69c200-66d4-11e9-8f13-47f2e8b3fe6a.png)

The upper part of the PCB:
![PCBtop](https://user-images.githubusercontent.com/37699408/56686645-b8245700-66d4-11e9-8bdc-55bc043bcbe0.png)

The bottom part of the PCB:
![PCBbottom](https://user-images.githubusercontent.com/37699408/56686658-c1adbf00-66d4-11e9-8c6a-260fb44c3ff9.png)


And finally the .zip file:
[BoB1.zip](https://github.com/gergelytakacs/AutomationShield/files/3113811/BoB1.zip)

**Comment by gergelytakacs** [comment]
Awesome, we'll check it out today. Only likely to add small changes:
- Mark the footprint of the mechanical connection on the "Top Assy" (gray)
layer, so we see where the 3D printed part goes.
- The GND of the potentiometer goes all the way to the right, to the C1.
There is a GND connector pin closer to the pot (Top left).
- The www address and the name, date on the top left corner should be
adjusted to the top. They are quite randomly thrown around...

**Comment by gergelytakacs** [comment]
@TiborKonkoly Please finish and post the final schematic plan and PCB design at most by Monday morning. I would like to order the PCB by Monday evening...

**Comment by TiborKonkoly** [comment]
Hello all! I have realised the requested changes and also  changed the board layout a bit, here are the results: 
![BoB_R1_Bottom](https://user-images.githubusercontent.com/37699408/56760628-e6b93500-679b-11e9-85ba-842c4c616c45.png)
![BoB_R1_Top](https://user-images.githubusercontent.com/37699408/56760632-e7ea6200-679b-11e9-869d-21d8d7e0bdf1.png)

- The POT was connected to the GND
- The placement of the 3D printed components is marked by the rectangles
- The text on the bottom is arranged
- I have also changed the diameter of the holes from 4mm to 3mm

Here is the included .zip file: 
[BoB_final.zip](https://github.com/gergelytakacs/AutomationShield/files/3118416/BoB_final.zip)

It should be ok, but please check it.  Have a nice weekend! :)

**Comment by gergelytakacs** [comment]
Looks good to me actually. Double check everything with a clear head until Monday, then I can push it to production.

@mgulan  @erik1392  please have a look at this and check the design, or else suffer in silence if something is not to your liking;)

**Comment by mgulan** [comment]
Looks allright to me too, incl. the small changes. I say go for the PCB order👍🏻

**Comment by gergelytakacs** [comment]
Thanks, will do. The TugShield (Evka) will be ordered too, but that project
is in a sorry state at the moment, she did not manage timing and scheduling
well.

**Comment by gergelytakacs** [comment]
![image](https://user-images.githubusercontent.com/37662064/56880394-ca97eb00-6a5c-11e9-8aad-ad8b29b18d7e.png)

![image](https://user-images.githubusercontent.com/37662064/56880420-e7ccb980-6a5c-11e9-8bc5-f02099259cee.png)

**Comment by gergelytakacs** [comment]
![image](https://user-images.githubusercontent.com/37662064/56880557-9244dc80-6a5d-11e9-8fb4-bce515aec6d5.png)

**Comment by gergelytakacs** [comment]
![image](https://user-images.githubusercontent.com/37662064/56883105-f9ff2580-6a65-11e9-9f1f-e31f7f502136.png)

**Comment by gergelytakacs** [comment]
![image](https://user-images.githubusercontent.com/37662064/56884694-e0141180-6a6a-11e9-8afa-b5428e7ba4a2.png)

**Comment by gergelytakacs** [comment]
Here is the "final" version that went in the production. The Wiki team will need these:
[BoBShield_R1_Final.zip](https://github.com/gergelytakacs/AutomationShield/files/3126564/BoBShield_R1_Final.zip)
[BoBShield_Production_R1.zip](https://github.com/gergelytakacs/AutomationShield/files/3126563/BoBShield_Production_R1.zip)

**Comment by raleh** [comment]
These zip files should be uploaded on some servers or can remain on github, i.e. to put them to github in the PCB lajout section, as You put them here?

**Comment by gergelytakacs** [comment]
All files must remain on GitHub. You have to use the AutomationShield.Wiki,
which is a separate repository from the AutomationShield code repository. I
have sent you an invitation, so you can use Git to manipulate it.


Best regards / S pozdravom / Udvozlettel;

Gergely Takacs, PhD.
Associate Professor
___________________________________________________
   web:       gergelytakacs.com
   e-mail: gergelytakacs@gergelytakacs.com
   mobile: +421(0)907 165 720


<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
I'm using Inbox When Ready
<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
to protect my focus.

**Comment by gergelytakacs** [comment]
![image](https://user-images.githubusercontent.com/37662064/57022389-45b0fb00-6c2f-11e9-862a-76de3ae42ea4.png)

**Comment by gergelytakacs** [comment]
@cortan @TiborKonkoly
PCB delivery is advised on next Thursday, I can bring it to school next Friday.

Make sure you follow up on the MOUSER order.

**Comment by gergelytakacs** [comment]
@Cortan @TiborKonkoly 
- My wife let me know that she's got the package from the PCB manufacturer.
- @Cortan Got an advisory from our economic system that the payment is in the process. You should try to get the official order form (signed (?) by the dean etc.) and send it to Mouser ASAP.

**Comment by gergelytakacs** [comment]
@corleone68 @Cortan @TiborKonkoly @raleh @lukasvadovic2 

![image](https://user-images.githubusercontent.com/37662064/57537987-b222ad00-7347-11e9-9cac-0f6c2c07a27c.png)
![image](https://user-images.githubusercontent.com/37662064/57538012-c070c900-7347-11e9-93c2-f23189b043a9.png)
![image](https://user-images.githubusercontent.com/37662064/57538019-c666aa00-7347-11e9-8c41-9200cad933ea.png)
![image](https://user-images.githubusercontent.com/37662064/57538028-cbc3f480-7347-11e9-86f9-5da0c53d9f6e.png)

**Comment by TiborKonkoly** [comment]
They look really good. I can´t wait to test them! :)

**Comment by gergelytakacs** [comment]
> They look really good. I can´t wait to test them! :)

Same here, man. :)

**Comment by gergelytakacs** [comment]
@Cortan @TiborKonkoly 

The package is in the lab, I've placed everything in the top drawer next to the door. I've checked everything except the FFC connectors, since I have no idea which ones you've chosen. Everything you ordered is there, except the 6 missing servos which (if we paid for them) @Cortan should make sure we also get it. The capacitors will be a bitch to solder on, since they have no side only bottom pads... But can be done, I've tried it - but you have to use a heat gun and it's a bit tricky.

Please note, mainly @TiborKonkoly, that I would like to see not only "kind of" working and assembled devices, but neat and precise work with the soldering etc. So don't rush it, take care that the end result looks nice and presentable.

**Comment by gergelytakacs** [comment]
@TiborKonkoly @Cortan 

Checked the connector it fits nicely. However, the cable is kinda "hard" I'd expect more flexibility. Might still work though. You should have used the really flat ~1 mm pitch type film ones...

Checked the ones @TiborKonkoly  ordered for the upcoming Link. The ones with the 2.54 mm pitch are of the same type - the wire is way too rigid for the Link shield. You will need to use the really flat ones with 1 / 0.5 mm pitch.
