### ISSUE TITLE
BoBShield: Generic software pointers

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#108]
- Do not print to serial by default from the library. No `Serial.print()' in these. That would assume that the user has initialized the `Serial` port, and we don't want that.
- Any self-test functionality should be implemented in a specific example. See e.g. [this](https://github.com/gergelytakacs/AutomationShield/tree/master/examples/MagnetoShield/Support/MagnetoShield_SelfTest).

**Comment by corleone68** [comment]
Okaay thanks for the info

**Comment by gergelytakacs** [comment]
Also checked the pinned Issue for software hints...

You should comment any generic idea on software development for the AS
project there.

G

**Comment by gergelytakacs** [comment]
![image](https://user-images.githubusercontent.com/37662064/56886184-ab09be00-6a6e-11e9-89a6-6e97407db536.png)

**Comment by gergelytakacs** [comment]
What is this? 

Is this necessary?


![image](https://user-images.githubusercontent.com/37662064/56886554-8c57f700-6a6f-11e9-898d-ad68fdf82363.png)

**Comment by gergelytakacs** [comment]
![image](https://user-images.githubusercontent.com/37662064/56886793-14d69780-6a70-11e9-9c3e-81f2242f395a.png)
This is fine, but
- Potentiometer not potenciometer
- Please comment line-by-line.

**Comment by corleone68** [comment]
First one is not used and needs to be removed. Initial idea was to create a function for BaudRate (found in libraries tutorials), but it not necessary. 

Second issue - debug() is used in FloatShield to check if sensor was initialized.

Third issue - yeaah typo :D

**Comment by gergelytakacs** [comment]
You can and should use a sort of debug functionality. Create an example
that provides a self-test function for the system. Look at the
MagnetoShield how this can be done.

g.

Best regards / S pozdravom / Udvozlettel;

Gergely Takacs, PhD.
Associate Professor
___________________________________________________
   web:       gergelytakacs.com
   e-mail: gergelytakacs@gergelytakacs.com
   mobile: +421(0)907 165 720


<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
I'm using Inbox When Ready
<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
to protect my focus.

**Comment by gergelytakacs** [comment]
Please comment your code!
![image](https://user-images.githubusercontent.com/37662064/58008735-55648680-7aed-11e9-89a8-5389fff84eec.png)
????
![image](https://user-images.githubusercontent.com/37662064/58008761-60b7b200-7aed-11e9-86ce-a61e64cd8cbe.png)

**Comment by gergelytakacs** [comment]
Hello there;

I've added CI for automated build checks. Your branch status is:
[![Build Status](https://travis-ci.org/gergelytakacs/AutomationShield.svg?branch=bobshield)](https://travis-ci.org/gergelytakacs/AutomationShield)
Every time you commit the entire system is automatically re-built. You can click on the link to see how this looks like.

**Comment by gergelytakacs** [comment]
According to @TiborKonkoly the temporary (from the mechanical standpoint) prototype based on the PCB is working. Please @lukasvadovic2 update the code ASAP and push to your branch, so I can review it...
