### ISSUE TITLE
BoBShield: Wiki

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#111]
Please use this for Wiki related communication.

Notes so far:
- All files (such as PCB layout and images) must remain on Git. The Wiki has its own repository, separate from the main one. Upload files there. 

@raleh

**Comment by raleh** [comment]
I created a wiki page for BOBShield here is the link https://github.com/gergelytakacs/AutomationShield/wiki/BOBShield. Look and give an opinion, what else should be added or edited. I wrote two sections on the wiki page. As for the SW team, I asked them to send me a code, but they replied that they would gladly send, but that their code still does not work. When they send me the code, then I will edit the Arduino Library section. Also Marek did not give me any of his documentation, so I can not continue any further.

**Comment by gergelytakacs** [comment]
Never really had any sorts of issues with this. When I clone it through GitHub desktop, I can work with it simply through the graphics interface. I cloned by clicking on the web Wiki, then I can  Push/Commit/Pull etc through the graphical software. I have never used the command line to work with the Wiki, so I don't know how that behaves. I cloned it locally several times without issues by this method.

Mine looks like this:
![image](https://user-images.githubusercontent.com/37662064/57382860-009c4400-71ae-11e9-912f-d670c7252304.png)

![image](https://user-images.githubusercontent.com/37662064/57382913-20336c80-71ae-11e9-8e4a-fe2a7c96a08e.png)
Thus my address is also `~.wiki.git`. I don't see an issue with that. You have to realize that the `Wiki` is most probably a repository on its own and behaves as any other repository.

I tried to pull from the command line, it works just fine:
![image](https://user-images.githubusercontent.com/37662064/57383056-67216200-71ae-11e9-8819-7fcc2c793c19.png)

**Comment by gergelytakacs** [comment]
Also, why do you live in the future?:) 
![image](https://user-images.githubusercontent.com/37662064/57383226-b10a4800-71ae-11e9-95b4-72c306119dec.png)

**Comment by raleh** [comment]
I had success in uploading new images and rar and zip files, so links were changed and they are downloadable. Now the problem is the table, I worked it through the Markdown Tables generator
![Table 1](https://user-images.githubusercontent.com/47608663/57544173-db970500-7356-11e9-8ee7-840df6a3d40b.jpg) 
![Table 2](https://user-images.githubusercontent.com/47608663/57544181-dfc32280-7356-11e9-9d8e-35c700862f4d.jpg)
and then I copied it into a git. But in the git will not appear as a table but as plain text. As You can see on https://github.com/gergelytakacs/AutomationShield/wiki/BOBShield. It's already going on my nerves, because the table will not appear as it should. I will now continue to add and improve descriptions in sections.

**Comment by mgulan** [comment]
Did you try to look at a wiki template of another AS shields?

**Comment by raleh** [comment]
Yes, I looked. They are same as my table, I don't know what the problem is.

**Comment by gergelytakacs** [comment]
> Yes, I looked. They are same as my table, I don't know what the problem is.

Have you looked if your text has any special characters that MarkDown may interpret differently? You can also try to send the table to me as - say - excel and I'll try to see what's wrong.

**Comment by gergelytakacs** [comment]
@raleh @mgulan 

You need a free line between text and table. It's fixed now. You are welcome. :)

**Comment by gergelytakacs** [comment]
@raleh 

Please make this "denser" and nicer, see HeatShield how:
![image](https://user-images.githubusercontent.com/37662064/57582369-35690d80-74c4-11e9-8bd2-cd09d415ac8d.png)

**Comment by gergelytakacs** [comment]
@raleh Please use less empty space with the renders. If the renders have a big enough resolution (they do, I've checked), you don't need new ones, just crop it out a bit.

![image](https://user-images.githubusercontent.com/37662064/57582382-72350480-74c4-11e9-890e-84df808e921f.png)

**Comment by gergelytakacs** [comment]
@raleh What causes the blue lines on the top and left of the PCB? If you can, please remove these.

![image](https://user-images.githubusercontent.com/37662064/57582400-b922fa00-74c4-11e9-9c26-bae0a21ddf81.png)

**Comment by gergelytakacs** [comment]
@raleh 

You may already write more on the methods used in the API! We already know what they *should* do - please consult with the software team.

![image](https://user-images.githubusercontent.com/37662064/57582421-eff91000-74c4-11e9-943a-0cd930265173.png)

**Comment by gergelytakacs** [comment]
@raleh 

Please use clickable links for the hardware. 

![image](https://user-images.githubusercontent.com/37662064/57582448-41a19a80-74c5-11e9-9904-eca0143448f7.png)

**Comment by raleh** [comment]
Thank You for correcting the table, I did changes You told me to change. I'm going to write to the software team, let them send me improved code description.

**Comment by gergelytakacs** [comment]
Welcome. We agreed today on how to proceed, so please do that.
