### ISSUE TITLE
TugShield: Thesis

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#120]
Thesis outline:

1. Úvod (1-2 s.)
2. Motivácia (5 s.)
3. Tvorba hardwaru (10-15 s.)
 - Komponenty
 - Vývoj predbežného protoypu
 - Vývoj plošného spoja
 - Finálny prototyp
4. Tvorba aplikačného rozhrania 
 - Knižnica AutomationShield (súčasný popis)
 - Vývoj API pre TugShield (progress, základné princípy, problém so Sampling etc., samotná trieda TugShield)
 - Metódy v TugShield (pod-podkapitoly pre každú metódu
5. Príklady 

6. Záver (1 s.)

**Comment by gergelytakacs** [comment]
@EvaVargova (A bit unrelated to the issue but) ...the PCB have arrived.
 
![image](https://user-images.githubusercontent.com/37662064/57538118-0168dd80-7348-11e9-8038-a3d08d97ddb2.png)
![image](https://user-images.githubusercontent.com/37662064/57538129-075ebe80-7348-11e9-9885-69e98a2ddce6.png)
![image](https://user-images.githubusercontent.com/37662064/57538143-0f1e6300-7348-11e9-8ebd-21569a033137.png)
![image](https://user-images.githubusercontent.com/37662064/57538152-13e31700-7348-11e9-9af3-9c8f08b008e6.png)
![image](https://user-images.githubusercontent.com/37662064/57538176-1fced900-7348-11e9-8025-fe7d69d4b33f.png)

**Comment by EvaVargova** [comment]
:D I am very happy....Thanks!

**Comment by gergelytakacs** [comment]
> :D I am very happy....Thanks!
I do hope the MOUSER parts will be here soon as well. Liaison w/ @Cortan about this, fingers crossed.

**Comment by gergelytakacs** [comment]
Thesis has been submitted.
