### ISSUE TITLE
TugShield: actuatorWrite();  (Arduino API)

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#122]
The TugShield `actuatorWrite()` will be a `void` function that takes a floating point number of the angle and then sets the servo to that certain angle. Please note, that the angle is always relative. It depends on what you choose and how you assemble the device. So you must really think about how to assemble it at the beginning, the angles way only make sense (across devices) then.

**Comment by gergelytakacs** [comment]
Note that this is related to #105

**Comment by gergelytakacs** [comment]
- Please change the name of this variable to something more sensible, e.g. `servo_angle`.
- I'm not sure what is the reason to have this variable as a public one, as opposed to simply let it live inside the method. It is after all not really needed anywhere else, or is it?
![image](https://user-images.githubusercontent.com/37662064/57670795-25127900-7611-11e9-9935-5112e1fae585.png)

**Comment by EvaVargova** [comment]
![obrázok](https://user-images.githubusercontent.com/44666023/57844702-e3c8c780-77d0-11e9-8e85-2986583e7030.png)
![obrázok](https://user-images.githubusercontent.com/44666023/57844737-f4793d80-77d0-11e9-88ec-f2bc7b0d6c4d.png)
I think Tugshield.h for some reason cant include Servo.h.
I have tried already this: 
![obrázok](https://user-images.githubusercontent.com/44666023/57844844-1bd00a80-77d1-11e9-83f7-cf5da56e209e.png)
and this:
![obrázok](https://user-images.githubusercontent.com/44666023/57844938-402be700-77d1-11e9-9819-73a8dc0bbcc8.png)
but still don't work.

**Comment by gergelytakacs** [comment]
You have not initialized the object `servo`. You have the class `Servo` but no object `servo`. In the beginning, you shall initialize the object by `Servo servo;`. Also please note that you are mixing the reference to the object (`servo`, upper code portion) with the class (`Servo`, lower code protion) that may create some trouble.

**Comment by gergelytakacs** [comment]
In your header, there are some issues with this, namely:
![image](https://user-images.githubusercontent.com/37662064/58149529-a8604a00-7c63-11e9-9ab4-0c0f2f7b0ffe.png)
- You don't need a variable in the prototype function, just the input argument type
- The type should be `float` and not `int`. Of course this affects the rest of your code (possibly)
