### ISSUE TITLE
TugShield: sensorRead();  (Arduino API)

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#123]
The TugShield `sensorRead()` method will take no arguments and will return the percentual deformation of the beam as a floating point number. Please use the `OptoShield` class as an inspiration.

First the method shall check if the user has run the `calibration()` method or not (see #121). This is based on a flag. If not you will set the minimal and maximal values to some sort of defaults, which you can determine based on experimentation. The analog reading can be then mapped (these are floats, so use `mapFloat()` from `AutomationShield` to give the percents.

**Comment by gergelytakacs** [comment]
Same issue as in #122. I do not think you need private variables in the class, as you do not share these *across* the methods. The only exception is `iscalibrated` (or whatever you call it), because that one you set in the calibration method, but use it in the sensor method.

![image](https://user-images.githubusercontent.com/37662064/57670911-a2d68480-7611-11e9-825f-8a3a8ad8ae56.png)

**Comment by EvaVargova** [comment]
![obrázok](https://user-images.githubusercontent.com/44666023/57762771-5fa70f00-7700-11e9-9ae4-1a6025d7b916.png)
I have a problem with this method....IDE show me this error:
![obrázok](https://user-images.githubusercontent.com/44666023/57762415-c4ae3500-76ff-11e9-98de-82929b42cd3d.png)
I really don't know where is the problem. Method should return float _sensorValue.

**Comment by gergelytakacs** [comment]
@EvaVargova

Allright. What does the `.h` say? Because it seems to me that your method prototype is incorrect.

Now I have looked at your `.h` and it prototypes `void sensorRead()` so that's why the compiler things these are actually two different methods, since have two different output types.

**Comment by gergelytakacs** [comment]
- Seems ok by visual inspection.
- Horizontal align the code lines nicer so it's more readable.
- English comments only.
