### ISSUE TITLE
TugShield: PID control example  (Arduino API)

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#126]
This will be an example that realizes PID control. You can use the HeatShield PID control example as a basis for your example. You must edit and think about
- The object name `TugShield` instead of `HeatShield` and of course the correct header
- Must set  a shorter sampling, probably on the order of 0.1 s
- Must set different trajectory according to your needs. The trajcetory (desired, setpoint) is in percents, your output should ideally reach these after a time.
- Must set a different length of an experimental section (T, in samples)
- Of course, and the hardest part is, to set a proper PID controller tuning.

**Comment by gergelytakacs** [comment]
Why would you use different sampling from the identification case? Please use the same sampling period (e.g. you can change the ID to 100)... 
![image](https://user-images.githubusercontent.com/37662064/57672356-12e80900-7618-11e9-9429-4fbf0c749178.png)

**Comment by gergelytakacs** [comment]
Same as in sampling. This should be set by experiment to look nice. Also the comment is wrong.
![image](https://user-images.githubusercontent.com/37662064/57672383-2eebaa80-7618-11e9-9a6a-d9efd74c5258.png)

**Comment by gergelytakacs** [comment]
- I can't really judge whether it works if I don't see any results.
- Please show a Serial Plotter output so I can see that it works.
- If you (and I) are satisfied with this, then you have to log the data in Matlab, as you need to show the results in a Matlab plot anyways. (in your thesis)

**Comment by gergelytakacs** [comment]
I see no change, improvement or results currently (22.5.2019, 8AM) -1

**Comment by EvaVargova** [comment]
Here in the output graph. It doesn't work at all.
![obrázok](https://user-images.githubusercontent.com/44666023/58193704-e0977500-7cc3-11e9-90a7-e40d71aabc79.png)
I think problem should be in two things: 
1. Problem with variable int - float for servo
2. Outputs from flexi are percentage values, but values written to servo aren't.

**Comment by gergelytakacs** [comment]
I agree with the possible issues with the types, but first you must be sure that your tuning is right after blaming it to somehting else.

I believe the green line is your input to your motor. As you can see it aggressively and violently switches to extremes, which is not what you what. So I think, that your PID tuning is definitely incorrect. The PID controller reacts to the small changes in your input (kind of noise) and blows it out of proportion. You need to experiment (a lot) with the tuning.
