### ISSUE TITLE
TugShield: Self-test example (Arduino API)

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#129]
This example performs a sort of self-test and diagnostics of the hardware device. It can also help to check the functionality of the assembled hardware. What it actually does depends on the possibilities of the hardware. You may base this one on the self-test example found amongst the MagnetoShield examples.

For example:
- Turn the servo to one end and see what the sensor reading gives. For this you must use the absolute values, not percents Determine some sort of range that can be considered "normal"
- Do the same to the other end.
- etc.

**Comment by gergelytakacs** [comment]
@EvaVargova 

Please push to your branch regularly, so I can check your progress. :) Thanks.

**Comment by gergelytakacs** [comment]
Do not forget about the self-test example.

**Comment by gergelytakacs** [comment]
I see no change, improvement or results currently (22.5.2019, 8AM) :-1:

**Comment by EvaVargova** [comment]
I have finished Self-test example. 
![obrázok](https://user-images.githubusercontent.com/44666023/58213786-ae9e0700-7cf3-11e9-9fab-75f959710356.png)
Maybe the range of "OK" is too wide, but in case it is narrower sometimes print "FAIL".

**Comment by gergelytakacs** [comment]
Ok, looks about right. But why are you mixing languages?:)
