### ISSUE TITLE
LinkShield: Hardware Design

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#132]
This issue is devoted to the generic hardware design issues of the upcoming LinkShield device. Post hardware design related issues and ideas here, unless the problem is big enough to deserve its own  issue.

**Comment by gergelytakacs** [comment]
Got these from eBay. They are 4 pin and look absolutely fine for hand soldering. Combine these with the strips I got earlier, and that's a pretty cool flexible lead to the end of the accelerometer. (Don't know if it analog or digital yet, but pretty sure you have to make your own breadboard - if possible).

![image](https://user-images.githubusercontent.com/37662064/57580127-de544000-74a5-11e9-8ccf-3a329bd2e07f.png)

**Comment by gergelytakacs** [comment]
*Motor selection*
- Try 120 degrees, with non-default signal width (according to datasheet).
- Try the analog output. What is the maximal amplitude of the singal?
- Take a full swing of rotation with the beam, try to see if the analog feedback detects any sorts of vibrations.

*How many g-s*
- First tests with 30 deg idicate 4 g.
- Take a full swing (120 deg) to see.
- The standard SG90 TowerPro servo had power issues. Try if a capacitor and diode solve it.

*Mechanical design*
- Turn the link to the correct position.

*Accelerometer selection*
- Which one can be hand-soldered.
- Candidates for accelerometers
- use soldering kit - learn to solder

* Cables *
- Study flat ribbon cables and connectors

**Comment by gergelytakacs** [comment]
- The feedback servo signal has voltage peaks on it, but it does not provide information about the vibrations. Conclusion: the feedback is not needed.
- Make screenshots with tests using a 90-120 degree sudden change of the beam, then test all the different accelerometers. Scale Y axis to "g"s or SI units. Use analog and digital too...
- Maximal acceleration is about 4 g.
- Analog seems to be better because of the limited resolution of digital.
- Try to determine which chips are hand solderable. Those with connections on the bottom we cannot do by hand. Try to look in forums if people mention hand soldering these.
- The FFC cables with 0.5 mm pitch seem to be the best. The connectors are hand-solderable.

**Comment by gergelytakacs** [comment]
Notes

- Motor current is seen on accelerometer.
- Other than that analoge looks good.
- Range is up to 3 G
- Why is the DC response of the accelerometer not 0?
- Digital looks acceptable, a bit of quantization is visible.
- 4 G range is recommended.
- All cheap accelerometers suitable for our purposes have contacts from the bottom.
- If the voltage peaks cannot be removed, all we have is the digital accelerometer.
- Cables: 0.5 mm pitch, 15 cm length.

Todo 21.11.2019
- [ ] Consult the 3D design w/ Erik
- [ ] Try to stabilize the supply of the analog accelerometer to see if it filters out peaks. 
- [ ] If you've picked an accelerometer, who sells it?
- [ ] Try to read up on the voltage spikes on the accelerometer signal.
- [ ] Do some *more* tutorials in DipTrace.
- [ ] Determine the placing of the servo. Don't forget about Due, Zero. Use a CAD redner from grabcad (or elsewhere) and play around with the placement.
- [ ] Give me a list of accelerometer candidates. (It wouldn't be bad if we had the same on a breakout.)
- [ ] Go to TME.sk and pick a suitable 0.5 mm pitch, 15 cm length and suitable connectors too.
- [ ] Look for a same sized servo (micro?) and see if there are any "faster". Faster is better.
- [ ] Start to write a "Motivation / Lit. review chapter of your thesis.

**Comment by martinvrican** [comment]
Accelerometer sensors used for testing: 
digital - ADXL345
analog - ADXL335

Results of tests with ADXL345 - 180, 60, 10 degrees
![digital180](https://user-images.githubusercontent.com/56957445/69323486-1d2e3400-0c47-11ea-9c55-73ace1c1ddf0.png)
![digital60](https://user-images.githubusercontent.com/56957445/69323580-4d75d280-0c47-11ea-924b-bd4a3e1ac8b7.png)
![digital10](https://user-images.githubusercontent.com/56957445/69323598-56ff3a80-0c47-11ea-84d6-4a39fba29a77.png)

Results of tests with ADXL335 - 180, 60, 10 degrees

![analog180](https://user-images.githubusercontent.com/56957445/69323740-90d04100-0c47-11ea-87f8-8a834aba3f8d.png)
![analog60](https://user-images.githubusercontent.com/56957445/69323750-97f74f00-0c47-11ea-984e-7c7e5a9ab4be.png)
![analog10](https://user-images.githubusercontent.com/56957445/69323767-9cbc0300-0c47-11ea-94e8-0b8294352370.png)

**Comment by gergelytakacs** [comment]
@martinvrican Thank you, excellent.

Can you please do a repeat measurement with the digital sensor
- with no weights on the beam and
- with weights that you think would be "normal" and appropriate to use?

**Comment by martinvrican** [comment]
TME.sk - pitch
https://www.tme.eu/sk/details/pca-6b-04-hu-3/konektory-ffc-fpc-raster-0-5mm/adam-tech/

https://www.tme.eu/sk/details/sfv4r-3stbe1hlf_c/konektory-ffc-fpc-raster-0-5mm/amphenol/sfv4r-3stbe1hlf/


Connector/ cable - I couldn't find good ribbon cables on TME.sk

**Comment by gergelytakacs** [comment]
@martinvrican 
Allright, got it. Thanks.

**Comment by gergelytakacs** [comment]
Consultation / todo 28.11.2019

- Peaks stayed unfortunately, that is why the decision is to go with digital.
- Will use the ADXL345.
- If we want to avoid outside supply, there are no faster servos. Faster servos usually use 6 V or hihger supply. We go SG92 or the SG90? Metal or plastic screw? 

- [ ] Decide on the servo.
- [ ] Determine the placing of the servo. Don't forget about Due, Zero. Use a CAD redner from grabcad (or elsewhere) and play around with the placement.
- [ ] Do some more tutorials in DipTrace.
- [ ] Consult the 3D design w/ Erik. Print your first candidate / idea by next week.
- [ ] Start to write a "Motivation / Lit. review chapter of your thesis.
- [ ] Draw the base PCB in an -almost- finished form.
- [ ] Look into the ways to program Arduino libraries. Consult the existing hardware, e.g. OptoShield, HeatShield, etc. You can also consult with FloatShield and MagnetoShield (quite complicated). Begin to write LinkShield API for Arduino.

**Comment by gergelytakacs** [comment]
ADXL345 breakout tutorial: https://learn.adafruit.com/adxl345-digital-accelerometer/downloads

![image](https://user-images.githubusercontent.com/37662064/69791882-aef8ec80-11c5-11ea-9469-6bfa265cb9d5.png)

![image](https://user-images.githubusercontent.com/37662064/69792123-3e9e9b00-11c6-11ea-958e-551c3bd2e293.png)

**Comment by martinvrican** [comment]
- simplified ADXL345 breakout and connection
![ADXL345-3-Axis-Accelerometer](https://user-images.githubusercontent.com/56957445/69796104-b4f2cb80-11cd-11ea-958b-a4968ba9f6e9.jpg)
![ADXL345-Connection-Diagram](https://user-images.githubusercontent.com/56957445/69796113-b8865280-11cd-11ea-993f-43142b50fded.jpg)
https://www.the-diy-life.com/how-to-connect-an-adxl345-3-axis-accelerometer-to-an-arduino/

**Comment by gergelytakacs** [comment]
@martinvrican Sure! These seem to be not 5V tolerant that is the only thing. However, mind you that judging by the photos may not be enough, as these breakouts might have parts on their other side.  In any case, our guess was correct - there are 2 pullups and a capacitor seen on these. You still need to figure out if you can leave the CS/SDO pins on floating or it is required to connect them to ground. The Adafruit one looked like it need to be grounded to set the address. Please have a look at the datasheet.

**Comment by gergelytakacs** [comment]
Oh okay. From the connections it seems that CS is on 3.3V, SDO is grounded. That is fine, you can do that on your own board, so it will only have a cap and the acceleometer on it. In any case, double check these connections in the datasheet so we don't make mistakes.

**Comment by gergelytakacs** [comment]
Note that the connectors from TME are at my home, will bring them in Monday. Stop by, and you can decide which one to use and which one to design on these boards.

**Comment by gergelytakacs** [comment]
@martinvrican New connectors arrived from TME, you can stop by monday:

![image](https://user-images.githubusercontent.com/37662064/69848418-5cc5d300-127a-11ea-8447-bfc4a4f8d92e.png)
![image](https://user-images.githubusercontent.com/37662064/69848452-6fd8a300-127a-11ea-9ba7-b3356919b3b9.png)

**Comment by gergelytakacs** [comment]
@erik1392 @martinvrican 

More connectors to choose from:

![image](https://user-images.githubusercontent.com/37662064/69946533-11b2f680-14ec-11ea-8eeb-916bfe20831a.png)

You can find it in your "drawer" in the lab, with your name on it.

**Comment by martinvrican** [comment]
https://componentsearchengine.com/ga/search.html?searchString=52745-0497

**Comment by martinvrican** [comment]
Servo
https://www.tme.eu/sk/details/kp-mb0090/servomotory/k-power/mb0090/

Connector
https://sk.farnell.com/molex/52745-0497/connector-ffc-fpc-4pos-1row-0/dp/2679573?st=52745-0497

**Comment by gergelytakacs** [comment]
![image](https://user-images.githubusercontent.com/37662064/70213120-e4a75380-1738-11ea-97b1-ddc6a510c00f.png)

**Comment by gergelytakacs** [comment]
@martinvrican @erik1392 The component list is as follows
100 nF 0805: https://www.tme.eu/sk/details/c0805c104m5rac/kondenzatory-mlcc-smd-0805/kemet/c0805c104m5ractu/10 uF, 1206, tantalum: https://www.tme.eu/en/details/t491a106m016at/smd-tantalum-capacitors/kemet/ Unfortunately I have not found 0805 at TME, so this is a bit larger.Servo: https://www.tme.eu/sk/details/kp-mb0090/servomotory/k-power/mb0090/22 uF, 0805, tantalum (instead of your too small 0.1 uF) for the Servo: https://www.tme.eu/en/details/tajr226m004rnj/smd-tantalum-capacitors/avx/ This is larger capacitance than your original intentions, I think it won't hurt at all.10 kOhm resistor 0805 https://www.tme.eu/en/details/smd0805-10k/0805-smd-resistors/royal-ohm/0805s8j0103t5e/  
Please re-design your boards accordingly, however, it seems to me that all the parts are compatible in their sizing to your original intentions, so no actual changes may be required.

@martinvrican  please upload your design files to the AutomationShield server so we can review and work on them. Please also put a screenshot of the current state here;) THank you:)

**Comment by gergelytakacs** [comment]
I'm re-posting from @martinvrican 's mail:
![image](https://user-images.githubusercontent.com/37662064/70454699-2b83a900-1aab-11ea-8795-74a45946250f.png)

Please @erik1392 have your say.

**Comment by erik1392** [comment]
looks OK for me. Just one thing... It may be useful to extend soldering pads further outwards in the accelerometer footprint for ease of hand soldering.

**Comment by gergelytakacs** [comment]
Good idea!

**Comment by gergelytakacs** [comment]
![image](https://user-images.githubusercontent.com/37662064/70514059-22d6b580-1b33-11ea-9eb7-c4088d7095cb.png) @erik1392 @martinvrican

**Comment by gergelytakacs** [comment]
@martinvrican @erik1392 - This is the breakout:
![image](https://user-images.githubusercontent.com/37662064/70515443-a2fe1a80-1b35-11ea-8b58-66d7b2de19ea.png)

**Comment by gergelytakacs** [comment]
![image](https://user-images.githubusercontent.com/37662064/70515606-eb1d3d00-1b35-11ea-9cb6-edfb5a3cf6f9.png)

**Comment by gergelytakacs** [comment]
@erik1392 @martinvrican 

![image](https://user-images.githubusercontent.com/37662064/70526188-56bcd580-1b49-11ea-8ddb-ed76af17f266.png)

**Comment by gergelytakacs** [comment]
@martinvrican @erik1392 

![image](https://user-images.githubusercontent.com/37662064/70533075-9343fd80-1b58-11ea-9999-c3372aacb812.png)
![image](https://user-images.githubusercontent.com/37662064/70533094-a0f98300-1b58-11ea-8d77-d4a7e7f89463.png)

Currently in audit.

![image](https://user-images.githubusercontent.com/37662064/70533252-fafa4880-1b58-11ea-9544-c425d5db5295.png)

**Comment by gergelytakacs** [comment]
@erik1392 @martinvrican 

In production:
![image](https://user-images.githubusercontent.com/37662064/70534215-dbfcb600-1b5a-11ea-81c0-4b052a189a8a.png)

**Comment by gergelytakacs** [comment]
Update: The components have arrived, I can bring them to the lab tomorrow.

**Comment by gergelytakacs** [comment]
@erik1392 @martinvrican 

Santa has came early. All will be in your drawer in the lab by tomorrow. Note that some components are shared between Magneto and Link, you might need to check that too. (I don't want to split the contents, because it would be hard to identify some components without the original bag.)

![image](https://user-images.githubusercontent.com/37662064/70657083-7a704080-1c5b-11ea-84ec-3bfa0dcddbae.png)

**Comment by gergelytakacs** [comment]
@martinvrican @erik1392 
Ho-ho-ho, Santa was here again. (I'll have it in the lab tomorrow.)

![image](https://user-images.githubusercontent.com/37662064/71084154-ed664380-2194-11ea-91f7-2309159fe432.png)
![image](https://user-images.githubusercontent.com/37662064/71084187-053dc780-2195-11ea-8c0c-44af6e4c7af1.png)
![image](https://user-images.githubusercontent.com/37662064/71084421-85fcc380-2195-11ea-94bc-d29ecbd42a24.png)

**Comment by gergelytakacs** [comment]
@martinvrican @erik1392 

Ho, ho, ho - Santa has visited us in D.S. today!:)

![image](https://user-images.githubusercontent.com/37662064/71286121-1dfdd700-2367-11ea-83e6-56a09fbae49c.png)
![image](https://user-images.githubusercontent.com/37662064/71286186-48e82b00-2367-11ea-9dc6-28de1bedc5e8.png)
![image](https://user-images.githubusercontent.com/37662064/71286216-61f0dc00-2367-11ea-845a-318198650512.png)
![image](https://user-images.githubusercontent.com/37662064/71286240-7339e880-2367-11ea-9baa-c5a842aab864.png)

**Comment by gergelytakacs** [comment]
@martinvrican @erik1392 

Oh, santa was late with these ones: ADXL345 breakouts for "cannibalizing" for our own ones:
![image](https://user-images.githubusercontent.com/37662064/71686914-d6cb0980-2d9c-11ea-95e3-4a3d9953498d.png)
![image](https://user-images.githubusercontent.com/37662064/71686927-e0ed0800-2d9c-11ea-8829-42060b5ac7d0.png)

**Comment by martinvrican** [comment]
It's cute, but will it work?
![20200109_152354](https://user-images.githubusercontent.com/56957445/72076260-8e0fd500-32f5-11ea-8f2e-b878c9ed1028.jpg)

**Comment by martinvrican** [comment]
Yes, it works!!!
![Komentár 2020-01-09 153809](https://user-images.githubusercontent.com/56957445/72076620-15f5df00-32f6-11ea-97b5-8f41c6084a82.png)

**Comment by gergelytakacs** [comment]
@martinvrican Yeah!!!!! Awesome!!!! You are the man!!!!!:)))) Nice job!
