### ISSUE TITLE
OptoShield LED too bright / major hardware issue

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#14]
@Gabor7697  has found out that the LED in the OptoShield is too bright, causing resolution and calibratin issues. At 5/255 analogWrite levels the sensor ouput is 900/1023; reducing resolution. Moreover according to him:
- The 10 k resistor for the LDR divider is not optimal, he calculated 2.3 kOhm (see below).
- A different colored LED can also help to reduce output.
- Larger LED resistor could reduce power. 

All of the solutions above should be possibly tested. 

@Gabor7697's calculations on a possible change in the LDR voltage divider.
![image](https://user-images.githubusercontent.com/37662064/38421551-cce9cff4-39a7-11e8-8b3d-ddf4fe3a8168.png)

The feedback process (because of the bad ranging) is not very nice, looks something like this:
![image](https://user-images.githubusercontent.com/37662064/38421713-5e1496e4-39a8-11e8-9495-d1dd765dfbc4.png)

**Comment by gergelytakacs** [comment]
@Gabor7697 pls. talk to @TiborKonkoly on possible HW changes when you can.

**Comment by Gabor7697** [comment]
Ok.

**Comment by gergelytakacs** [comment]
@Gabor7697 and @TiborKonkoly  have patched the shield successfully. @TiborKonkoly  should (after his thesis) modify the remaining boards. Do not forget to update any documentation, e.g. the wiki!
