### ISSUE TITLE
Adafruit_VL53L0X library

### ISSUE THREAD

**Issue by Gabor7697** [gergelytakacs/AutomationShield#15]
It's impossible to reverse engineer this : https://github.com/adafruit/Adafruit_VL53L0X/tree/master/src

**Comment by gergelytakacs** [comment]
Well, not impossible but quite complex and probably does not worth the trouble.

As a far as I understand, this takes a library from STM and just wraps it for the arduino. Maybe this could actually be done, but for now just put it on hold, there are more pressing issues to solve.

**Comment by gergelytakacs** [comment]
Lets leave this issue on the sidelines and re-visit (possibly) later. Assume the user has thid library installed and we go from there.

**Comment by gergelytakacs** [comment]
The library is not really worth re-doing. It has been now submoduled to the this project, this way it is accessible for the user without external installation.
