### ISSUE TITLE
Scheme update Opto

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#17]
Tibor updated the scheme for the opto Wiki. Please also
- update the file on the wiki
- update the picture of the schematics on wiki

**Comment by TiborKonkoly** [comment]
Finally done, I updated the schematics and the file too. It took me some time ( and some changes) but it is good now, I think. Check it please.

**Comment by gergelytakacs** [comment]
Awesome,  thank you!

One little note: in the schematic file that you've uploaded (DIP) change the wire colors back to something visible in DIP trace.  I know that you've changed it to create the image, but the schematics needs to remain readable in DIPTrace!

**Comment by TiborKonkoly** [comment]
Ready, I changed the colours of some traces, check it please.
