### ISSUE TITLE
Simulink links broken for Heat and Opto

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#187]
@PeterChmurciak Since you've changed the name of the individual block libraries for "Opto" and "Heat" (because of the reserved "Float" issue), the examples for Opto and Heat ceased to work. Please take a look at these examples and fix the missing blocks, possibly by replacing them with the new ones. Example:

![image](https://user-images.githubusercontent.com/37662064/63345180-72119400-c352-11e9-8d33-d1585e83fa5c.png)
or
![image](https://user-images.githubusercontent.com/37662064/63345585-5a86db00-c353-11e9-84d8-250482a9b295.png)

**Comment by PeterChmurciak** [comment]
@gergelytakacs Hmm, thats weird because I have no such problem. Possibly you have to use `installForSimulink.m` and/or `slblocks.m` functions from `/simulink` folder in order for it to appear and work normally ? Can you please try that ? Because I do not have this issue so solving it is quite troublesome for me.

**Comment by gergelytakacs** [comment]
@PeterChmurciak  I can confirm the problem exists. I have removed the path definitions from the computer, re-ran the add scripts with the same results. If you open an example from Opto or Heat, you see the missing links. By pure chance, I got a new laptop where I had to do a clean install of Windows/Matlab/Git etc. The problem still persists.

If you look at the properties of the missing block, you see that it refers to the library module by the old name, e.g. Opto and Heat. It is enough to re-write the definitions to the new ones, I think:
![image](https://user-images.githubusercontent.com/37662064/63668146-87fdd980-c7d6-11e9-8c5b-43ad7c4c7bae.png)

**Comment by PeterChmurciak** [comment]
@gergelytakacs You were right about the bug, I have not opened the examples before - tried it only by using the blocks in new model... Sorry about that.

I have fixed the examples in c8a56ac. Tried to run/build them to make sure that they seem to work. Only issue was with `Sensor Read` block of `OptoShield`. There was a bug in the block mask:
![optoProb](https://user-images.githubusercontent.com/51911541/63808092-7542ec00-c91f-11e9-9cdc-e2c42af4b7e3.png)

The `Parameter3` should have been called `Ts` for the block to work, for some reason it was like this so I have fixed that.

All Simulink examples should work now, please check if the issue has been resolved.

**Comment by gergelytakacs** [comment]
#c8a56ac Fixes this.

**Comment by gergelytakacs** [comment]
@PeterChmurciak Thank you for fixing this issue! I have no idea what the problem was with Opto, since I used it before, but oh well. :) I can confirm that your commit fixed the issue.
