### ISSUE TITLE
Auxiliary LED and LDR pins

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#2]
The `Optical.begin` method should also initialize the auxiliary LED and LDR pins.

**Comment by TiborKonkoly** [comment]
Csak egy kérdésem lenne, nem a projekttel kapcsolatban, elfelejtettem ott
megkérdezni, de nemtudja hogy lesz jovo héten a tanítás?

2018-03-26 22:25 GMT+02:00 Gergely Takács <notifications@github.com>:

**Comment by TiborKonkoly** [comment]
Done, the Optical.begin function initializes the auxiliary pins, both LDR and LED. But the auxiliary LED does not need an own line, because it is connected to the LED in the tube, so the line pinMode(OPTO_UPIN,OUTPUT); initializes both LEDs.

**Comment by gergelytakacs** [comment]
Sure, that's correct!
