### ISSUE TITLE
MagnetoShield: Latest API fails to build

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#205]
@KuboJakub @erik1392 

According to Travis CI, the latest version of the API does not work very well, actually it does not even compile. Please check out the issues and fix them. See the [Travis CI Logs](https://travis-ci.org/gergelytakacs/AutomationShield/builds/650822030) for more information.

**Comment by KuboJakub** [comment]
Okay, already fixed.

**Comment by gergelytakacs** [comment]
@KuboJakub 

Nice job. In such cases, you may close the issue (next time).
