### ISSUE TITLE
MagnetoShield R4->R5

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#234]
Ideas for next MagnetoShield

- If the magnet only needs 60 mA, why don't we use an onboard boost converter? (Instead of the 12 power supply).

G

**Comment by KuboJakub** [comment]
The issue is that the magnetic force depends on the current, not the voltage. If we use boost convertor we get more volts with smaller current, so i am afraid that is not going to help us...but not sure! so worthy to consider this case.
