### ISSUE TITLE
Sampling time as a globally accessible variable

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#28]
Make sure that when the user initializes sampling time for the sampler function, the variable can be used elsewhere, eg. In the PID function.

**Comment by TiborKonkoly** [comment]
Done, now Ts acts as a globally accessible variable for storing the value of the sampling time. I tried it, worked.

**Comment by gergelytakacs** [comment]
Ts should not be float.

**Comment by gergelytakacs** [comment]
@rkoplinger solution should be used with the "GetSampling" (or whatever) function to access sampling times inside functions, like the PID. Please remember @Gabor7697 @TiborKonkoly @KuboJakub when adding new features to the library.
