### ISSUE TITLE
Synology stays down after power cycle

### ISSUE THREAD

**Issue by erik1392** [gergelytakacs/AutomationShield#315]
@gergelytakacs  Synology stays down after the power cycle, set automatic boot up.

**Comment by gergelytakacs** [comment]
![image](https://user-images.githubusercontent.com/37662064/165348127-256f7efe-e8c6-4a48-9465-0c54ad23d1f9.png)

**Comment by gergelytakacs** [comment]
@erik1392 I hope this fixes the issue, if not, reopen this issue.
