### ISSUE TITLE
AeroShield compilation error

### ISSUE THREAD

**Issue by benodomi** [gergelytakacs/AutomationShield#357]
When setting macro #define MANUAL1 in AeroShield_EMPC.ino I've got a compilation error because r has no type.

**Comment by benodomi** [comment]
After turning with knob reference doesn't change. Adding a line Xr[1] = r;  on line 104 fixs this.

**Comment by gergelytakacs** [comment]
Hello @benodomi and we appreciate the feedback. @erik1392 this is a quick fix - can you please implement it? I don't want to do it without testing.

**Comment by erik1392** [comment]
"I'm aware of the bug. There are more like it. The AeroShield_eMPC branch is still under development, hence, it has not yet been merged into the master branch."

**Comment by benodomi** [comment]
I've already used this code during Workshop and project work. Sorry for this way of sharing code but this piece of code is with all fixes related to this issue:

```
  #if MANUAL
    float r =  AutomationShield.mapFloat(AeroShield.referenceRead(),0,100,0,M_PI);          //--Sensing Pot reference
    Xr[1] = r;        
  #elif !MANUAL
    if(i >= sizeof(R)/sizeof(float)){ // If trajectory ended
      AeroShield.actuatorWriteVolt(0.0); // Stop the Motor
      while(true); // End of program execution
    }
    if (k % (T*i) == 0){ // Moving through trajectory values    
    //r = R[i];
    Xr[1] = R[i];
      i++;             // Change input value after defined amount of samples
    }
    k++;                              // Increment
  #endif
```

**Comment by erik1392** [comment]
Thank you, I will integrate your code.
