### ISSUE TITLE
Magnetoshield 3D parts

### ISSUE THREAD

**Issue by alphalambdaepsilonxi** [gergelytakacs/AutomationShield#371]
Dear Sir or Madam,

the 3D print files for the Magneto shield are missing.
Could you please upload them?

Many Thanks!

**Comment by erik1392** [comment]
Hello, 
sorry for that, the files in the wiki are not well-maintained.  I created a [new repo for hardware](https://github.com/erik1392/AutomationShield-Hardware/tree/main/MagnetoShield/R4/3D_printed_parts). Eventually, hardware files for all Shields will be there.
