### ISSUE TITLE
Naming of the "ball blower thingy"

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#5]
Find a good name for the ball blower thingy.  Inspire by the existing naming scheme *Opto* and *Moto*

**Comment by mgulan** [comment]
Something like BlowJobShield... ?

Naaah, I am kidding, I meant **FloatBallShield** / FloatShield / ...

**Comment by gergelytakacs** [comment]
Hmm. FloatShield is not bad. Any other ideas from @Gabor7697  and co. ?:)

**Comment by gergelytakacs** [comment]
WindShield :)

**Comment by Gabor7697** [comment]
BongShield

**Comment by mgulan** [comment]
yeah, right..:D

I think FloatShield (familiarly Floaty) sounds good.

**Comment by gergelytakacs** [comment]
Ok, unless the group comes up with a better name, I can live with FloatShield. @Gabor7697 can you please liaison with the group and see if you can come up w/ something better? Or if this is okay for you guys?

**Comment by Gabor7697** [comment]
FloatShield is okay for us.

**Comment by gergelytakacs** [comment]
All right, FloatShield it is! Agreed.

:)

g

Best regards / S pozdravom / Udvozlettel;

Gergely Takacs, PhD.
Associate Professor
___________________________________________________
   web:       gergelytakacs.com
   e-mail: gergelytakacs@gergelytakacs.com
   mobile: +421(0)907 165 720
