### ISSUE TITLE
VibroShield: Clamp

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#61]
Design the clamp. The clamp holds the beam.

- It must be cheap, simple. 
- Prefer off-the shelf clamps and mechanisms.

**Comment by KuboJakub** [comment]
So idea with 2 metal pillars and screws with washers binding vibring stripe up is not good?
Between each washer and stripe would be isolation gum circle to eliminate crossing vibration from stripe on arduino
https://www.tme.eu/sk/details/tff-m8x30_dr1213/distancne-prvky-kovove/dremec/1213x30/

**Comment by gergelytakacs** [comment]
Actually, we I was thinking of 3D printing the superstructure. One feature could be possibly added - a screw-type height adjustment of the magnet.

**Comment by gergelytakacs** [comment]
It's quite hard for me to imagine what you mean. Maybe attach a drawing?

**Comment by KuboJakub** [comment]
![img_4332](https://user-images.githubusercontent.com/38165551/48954022-1b546680-ef48-11e8-9e69-d7b16fb4dae6.JPG)

**Comment by gergelytakacs** [comment]
It's a beginning, but keep thiking.
How about sideways placement?

Best regards / S pozdravom / Udvozlettel;

Gergely Takacs, PhD.
Associate Professor
___________________________________________________
   web:       gergelytakacs.com
   e-mail: gergelytakacs@gergelytakacs.com
   mobile: +421(0)907 165 720


<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
I'm using Inbox When Ready
<https://inboxwhenready.org/?utm_campaign=signature&utm_medium=email&utm_source=signature>
to protect my focus.
