### ISSUE TITLE
Fill out required components in Opto Wiki

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#7]
@TiborKonkoly  please fill out the table with the components required to make an OptoShield

**Comment by gergelytakacs** [comment]
Remains open, as there are likely changes due to bug in #14

**Comment by gergelytakacs** [comment]
Bug #14 has been mended, but the list is likely to be old.

**Comment by TiborKonkoly** [comment]
The list is up to date, I refreshed it.

**Comment by gergelytakacs** [comment]
Awesome, tank you!
