### ISSUE TITLE
Naming Ball on (in) beam

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#86]
We need to name our future "child". It's traditionally called "ball on beam" experiment, so in accordance with the naming conventions it should be BallOnBeamShield, but that's too long. I'm open to suggestions.

- BobShield?
- BallShield
- ... ?

**Comment by mgulan** [comment]
BoBShield

**Comment by gergelytakacs** [comment]
It shouldn't be BallShield, because [of unspeakable things](https://www.youtube.com/watch?v=3ew06J05pkk).

**Comment by gergelytakacs** [comment]
The student team has picked BOBShield

**Comment by mgulan** [comment]
Great, yet I still think BoBShield is more elegant and fitting.
