### ISSUE TITLE
HeatShield: Wiki update

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#88]
The wiki page for the HeatShield should be updated. This page is cited in the paper and the paper is accepted. There are several issues with the page as it is currently:

- Student written, so full of language and other types of mistakes
- The API for the Arduino has been re-vamped, so several commands they cite there currently are changed around.
- There is now a Matlab and Simulink API as well, this is not even mentioned there.
- The examples have been re-done.
- There are new, better photos.

I do not think that even copy-pasting from the article is an issue here, however it should be less 'sciency' and more friendly to the expected target audience: e.g. students. I can supply more "raw" photos from the photo-shoot too.

**Comment by mgulan** [comment]
Done with the necessary version of Wiki.
Will work on possible improvements on the fly.
